// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace BridgeVueApp
{
    public partial class ML_Class_Success
    {
        /// <summary>
        /// model input class for ML_Class_Success.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Grade")]
            public float Grade { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Ethnicity")]
            public string Ethnicity { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"SpecialEd")]
            public bool SpecialEd { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"IEP")]
            public bool IEP { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"EntryReason")]
            public string EntryReason { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"PriorIncidents")]
            public float PriorIncidents { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"OfficeReferrals")]
            public float OfficeReferrals { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Suspensions")]
            public float Suspensions { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Expulsions")]
            public float Expulsions { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"EntryAcademicLevel")]
            public string EntryAcademicLevel { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"EntrySocialSkillsLevel")]
            public string EntrySocialSkillsLevel { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"AvgVerbalAggression")]
            public float AvgVerbalAggression { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"AvgPhysicalAggression")]
            public float AvgPhysicalAggression { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"AvgAcademicEngagement")]
            public float AvgAcademicEngagement { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"RedZonePct")]
            public float RedZonePct { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"ExitReason")]
            public string ExitReason { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"LengthOfStay")]
            public float LengthOfStay { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ML_Class_Success.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Grade")]
            public float Grade { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"Ethnicity")]
            public float[] Ethnicity { get; set; }

            [ColumnName(@"SpecialEd")]
            public float[] SpecialEd { get; set; }

            [ColumnName(@"IEP")]
            public float[] IEP { get; set; }

            [ColumnName(@"EntryReason")]
            public float[] EntryReason { get; set; }

            [ColumnName(@"PriorIncidents")]
            public float PriorIncidents { get; set; }

            [ColumnName(@"OfficeReferrals")]
            public float OfficeReferrals { get; set; }

            [ColumnName(@"Suspensions")]
            public float Suspensions { get; set; }

            [ColumnName(@"Expulsions")]
            public float Expulsions { get; set; }

            [ColumnName(@"EntryAcademicLevel")]
            public float[] EntryAcademicLevel { get; set; }

            [ColumnName(@"EntrySocialSkillsLevel")]
            public float[] EntrySocialSkillsLevel { get; set; }

            [ColumnName(@"AvgVerbalAggression")]
            public float AvgVerbalAggression { get; set; }

            [ColumnName(@"AvgPhysicalAggression")]
            public float AvgPhysicalAggression { get; set; }

            [ColumnName(@"AvgAcademicEngagement")]
            public float AvgAcademicEngagement { get; set; }

            [ColumnName(@"RedZonePct")]
            public float RedZonePct { get; set; }

            [ColumnName(@"ExitReason")]
            public uint ExitReason { get; set; }

            [ColumnName(@"LengthOfStay")]
            public float LengthOfStay { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ML_Class_Success.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("ExitReason");
            if (labelColumn == null)
            {
                throw new Exception("ExitReason column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
